### ISSUE TITLE
Too Few DadVices

### ISSUE THREAD

**Issue by houtan1** [houtan1/DadVice_V01#3]
* the list of DadVices provided in dadViceDB.txt is too small
* we should add more dadVices
  * manually come up with original ones
  * source them (references)

**Comment by houtan1** [comment]
1. remove unoriginal content
2. create google docs and share
3. set timelines and dadvice number goals
4. copy original compiled list of dadvices into dadViceDB.txt at deadline
5. ready for release version 1

**Comment by SpencerTaft** [comment]
Goal until next meeting:
* Minimum 5 new dadvices/day
* read teammate's 5+ dadvices each day
* 7 days till next meeting, that's 7*5*2 new dadvices=70 dadvices
